apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/thomas-mattsson/s2i-ace/7dcca2c429dd9ace5c4f1cd5a86fd783ef851708/tekton/tasks/s2i-ace-task.yaml
