apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-customizations
spec:
  project: default
  source:
    repoURL: https://github.com/Nordic-MVP-GitOps-Repos/cp4i-gitops-appset.git
    targetRevision: HEAD
    path: 'argocd/customizations'
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      selfHeal: true

