apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cp4i
spec:
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          - list:
              elements:
               - namespace: dev
                 path: envs/dev/overlays/azure
                 cluster: https://kubernetes.default.svc
                 argoproject: default
                 revision: HEAD
               - namespace: prod
                 path: envs/prod/overlays/azure
                 cluster: https://kubernetes.default.svc
                 argoproject: default
                 revision: HEAD
          - list:
              elements:
                - name: mq
  template:
    metadata:
      name: '{{name}}-{{namespace}}'
    spec:
      project: '{{argoproject}}'
      source:
        repoURL: https://github.com/Nordic-MVP-GitOps-Repos/cp4i-gitops-appset.git
        targetRevision: '{{revision}}'
        path: '{{path}}/{{name}}'
      destination:
        server: '{{cluster}}'
        namespace: 'cp4i-{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
