kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-mq-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - cert-manager.io
      - mq.ibm.com
    resources:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-mq-rolebinding
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-mq-role