apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  name: common-service
spec:
  requests:
  - operands:
      - name: ibm-cert-manager-operator
    registry: common-service
    registryNamespace: ibm-common-services
