apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qm-three
spec:
  license:
    accept: true
    license: L-RJON-C7QG3S
    metric: VirtualProcessorCore
    use: NonProduction
  queueManager:
    route:
      enabled: true
    name: QMTHREE
    availability:
      type: SingleInstance
    storage:
      queueManager:
        type: ibmc-block-gold
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 1Gi
    mqsc:
    - configMap:
        name: queue-manager-three-ha-mi-configmap
        items:
        - tls.mqsc
  version: 9.2.5.0-r3
  web:
    enabled: true
