apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../../components/mq/base
- ../../../../components/mq/operator/base
- ../../../../components/mq/certs/base

resources:
- namespace.yaml
- operatorgroup.yaml

patchesStrategicMerge:
- version.yaml
- license.yaml
- cert-dns-names.yaml
